// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTraining.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220211172311_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a51b2d0a-5960-48b1-a9cf-edfe89e369de"),
                            Address = "Elfateh, Tanta",
                            Country = "Egypt",
                            Name = "InnoTech"
                        },
                        new
                        {
                            Id = new Guid("558d3d58-915f-4611-b22d-7ef105146956"),
                            Address = "London",
                            Country = "England",
                            Name = "SpaceX"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b2f6d86-47b3-4a9b-ad63-6efd59de2390"),
                            Age = 21,
                            CompanyId = new Guid("a51b2d0a-5960-48b1-a9cf-edfe89e369de"),
                            Name = "Mohammad Fayed",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("1526420e-e93e-467a-8ce5-103faef83fde"),
                            Age = 21,
                            CompanyId = new Guid("558d3d58-915f-4611-b22d-7ef105146956"),
                            Name = "Fatma Farag",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("07691a34-b2ff-4997-9d15-894f085c7a40"),
                            Age = 22,
                            CompanyId = new Guid("558d3d58-915f-4611-b22d-7ef105146956"),
                            Name = "Salma Negm",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("3f6b994b-3b75-451a-a174-cfb1acc63d40"),
                            Age = 30,
                            CompanyId = new Guid("a51b2d0a-5960-48b1-a9cf-edfe89e369de"),
                            Name = "Abdullah Elhanafy",
                            Position = "Business Analist"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
